# -*- coding: utf-8 -*-
"""Mobilenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VoyT0oXL_QiBOOfTd7ZKdiRKyysiukjI
"""



import torchvision.models as models
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader, random_split
import torch.optim as optim
import torch.nn.functional as F
import torch.nn as nn
import matplotlib.pyplot as plt
import numpy as np
import zipfile
from torchvision.models.detection import roi_heads
#net = models.resnext50_32x4d(weights=True)
#net = models.resnext50_32x4d(weights=True)
net = models.resnext50_32x4d(weights=True)
#net.cuda()
#net=torch.load('resnext.pth')
#net=Net()
#net='resnext.pth'
#net.load_state_dict(torch.load('resnext.pth'))
#net.weights=models.ResNeXt50_32X4D_Weights.DEFAULT
data_dir = 'drive/MyDrive/tum_pancr.zip'
#data_dir = 'tum_pancreatice'

zip_ref = zipfile.ZipFile(data_dir, "r")
zip_ref.extractall()
zip_ref.close()


transform = transforms.Compose([
        transforms.RandomRotation(90),
        transforms.RandomRotation(180),
        transforms.RandomRotation(270),
        transforms.Resize(224),
        transforms.CenterCrop(224),
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomAffine(0, [0.9,0.9], [0.9, 1.1]),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),])

trainset = datasets.ImageFolder('tum_pancreatice/train', transform=transform)
testset = datasets.ImageFolder('tum_pancreatice/test', transform=transform)

trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True, num_workers=2)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=False, num_workers=2)

classes = ('non-tum', 'tum')
num_ftrs = net.avgpool.output_size
print('num_ftrs')
print(num_ftrs)
net.fc = nn.Linear(2048, 2)

for name, layer in net.named_modules():
        print(name, layer)

#net.load_state_dict(torch.load('drive/MyDrive/resnexxt_1_4000epochs.pth',  map_location=torch.device('cpu')))

if torch.cuda.is_available():
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    net.cuda()

criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(net.parameters(), lr=0.0001, momentum=0.9)
print('parameters')
print(net.parameters())
min_valid_loss = np.inf

total=0
correct=0

for epoch in range(0,  100):  # loop over the dataset multiple times

    running_loss = 0.0
    losses = []
    #net.cuda()
    net.train()
    for i, data in enumerate(trainloader, 0):
        inputs, labels = data
        #inputs, labels = inputs.to(device), labels.to(device)
        #inputs.unsqueeze()

        # zero the parameter gradients
        optimizer.zero_grad()

        # forward + backward + optimize
        #net.cuda()
        outputs = net(inputs)
        #print('outputs:')
        #print(outputs)
        #print('labels:')
        #print(labels)
        #print('Correct: %d' % correct)
        #labels = labels.unsqueeze(1).float()
        #pred = max(outputs, 1)
       # m=torch.sigmoid(inputs)
        _, predicted = torch.max(outputs.data, 1)
        #print('predicted')
        #print(predicted)
        #predicted=predicted.cuda()
        loss = criterion(outputs, labels)
        #predicted = net(torch.from_numpy(indices))
        #motor_controls = predicted.clone().detach().numpy()
        #loss = criterion(predicted.float(), labels.float())
        #loss=loss.cuda()
        #predicted=predicted.to(device).long()
        #loss=criterion(predicted.float(), labels.float())
        #loss.requires_grad = True
        loss.backward()
        optimizer.step()
        #optimizer.step()

       # _, predicted = torch.max(outputs.data, 1)
        total+= labels.size(0)
        correct+= (predicted == labels).sum().item()

        losses.append(loss.item())

        # print statistics

        running_loss += loss.item()
        #if i % 2000 == 1999:    # print every 2000 mini-batches
        print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
        #running_loss = 0.0

    #valid_loss = 0.0
    #net.eval()     # Optional when not using Model Specific layer
    #for j, data1 in enumerate(validloader,0):
        #if torch.cuda.is_available():
           # data1, labels = data1.cuda(), labels.cuda()
        #inputs1, labels1 = data1
        #target = net(inputs1)
        #loss = criterion(target,labels1)
        #valid_loss = loss.item() #* data.size(0)
        #print(f'Epoch {epoch+1} \t\t Training Loss: {running_loss} \t\t Validation Loss: {valid_loss}')
    #if min_valid_loss > valid_loss:
        #print(f'Validation Loss Decreased({min_valid_loss:.6f}--->{valid_loss:.6f}) \t Saving The Model')
        #min_valid_loss = valid_loss

    #roi_heads.mask_rcnn_loss = loss*(1-correct/total)



plt.plot(losses, label='Training loss')
plt.show()
print('Finished Training')
print('Correct: %d' % correct)
print('Accuracy of the network on the %d training set images: %d %%' % (len(trainset),
    100 * correct / total))

PATH = 'drive/MyDrive/resnexxt_1_4200epochs.pth'
torch.save(net.state_dict(), PATH)

net.load_state_dict(torch.load(PATH))

#evaluare retea pe setul de test
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images, labels = data
        images, labels = images.to(device), labels.to(device)
        outputs = net(images)
        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
print(total)
print(correct)

print('Accuracy of the network on the %d test images: %d %%' % (len(testset),
    100 * correct / total))



#
#
# from google.colab import drive
# drive.mount('/content/drive')
#
#
#
#
#
#
#
#
#
# unzip tum_pancr.zip
#
#
#
# !unzip val.zip
#
# """# New Section"""